# Generated by Django 3.2.6 on 2021-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('degree', models.CharField(choices=[('mutaxasis', 'Mutaxasis'), ('ikkinchi', 'Ikkinchi toifa'), ('birinchi', 'Birinchi toifa'), ('oliy', 'Oliy toifa')], default='mutaxasis', max_length=20)),
                ('grade', models.CharField(choices=[('direktor', 'Direktor'), ('mmibdu', "MMIBDO'"), ('uibdu', "O'IBDO'"), ('uqtuvchi', "O'qtuvchi"), ('psixolog', 'Psixolog')], default='uqtuvchi', max_length=20)),
                ('image', models.ImageField(blank=True, default='teachers/no_image.png', upload_to='teachers/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='inactive', max_length=10)),
                ('science', models.ManyToManyField(to='index.Science')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
    ]
